const {chromium,expect}=require('playwright/test');
const assert=require('node:assert/strict');

(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  try{
    const page=await browser.newPage({viewport:{width:390,height:844}});
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto(process.env.TEST_URL||'http://127.0.0.1:5173');
    await page.waitForLoadState('networkidle');
    const saved=()=>expect(page.locator('#save-state')).toHaveText('Сохранено');
    await saved();
    await page.getByRole('button',{name:'Настройки',exact:true}).click();
    await page.getByRole('button',{name:'Открыть каталог',exact:true}).click();
    await page.getByRole('searchbox',{name:'Поиск упражнений'}).fill('жим');
    const count=await page.locator('.catalog-item').count();
    await page.locator('.catalog-item').first().getByRole('button',{name:/Техника/}).click();
    const techniqueTitle=await page.locator('#sheet-title').innerText();
    await page.getByRole('button',{name:'Мои заметки и настройки'}).click();
    await page.locator('#close-sheet').click();
    await expect(page.locator('#sheet-title')).toHaveText(techniqueTitle);
    await page.locator('#close-sheet').click();
    await expect(page.getByRole('searchbox')).toHaveValue('жим');
    assert.equal(await page.locator('.catalog-item').count(),count);
    await page.locator('.catalog-item').first().getByRole('button',{name:/Техника/}).click();
    await page.getByRole('button',{name:'Мои заметки и настройки'}).click();
    await page.getByLabel(/^Мои заметки/).fill('Проверка возврата после сохранения');
    await page.getByRole('button',{name:'Сохранить',exact:true}).click();
    await expect(page.locator('#sheet-title')).toHaveText(techniqueTitle);
    await expect(page.getByText('Проверка возврата после сохранения',{exact:true})).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.getByRole('searchbox')).toHaveValue('жим');
    await page.locator('#close-sheet').click();
    await expect(page.locator('#sheet')).not.toBeVisible();

    await page.getByRole('button',{name:'Тренировка',exact:true}).click();
    await page.getByRole('button',{name:'Начать тренировку',exact:true}).click();
    const first=page.locator('.exercise').first();
    await first.locator('.set-row input').nth(0).fill('80,5');
    await first.locator('.set-row input').nth(1).fill('10');
    await saved();
    await expect(page.locator('[data-workout-count]')).toContainText('1 /');
    assert.equal(await page.getByRole('button',{name:/выполнен/}).count(),0);
    await first.getByRole('button',{name:'+ Добавить подход',exact:true}).click();
    await expect(first.locator('.set-row').last().locator('input').nth(1)).toHaveValue('');
    await saved();await page.reload();await saved();
    await expect(page.locator('[data-workout-count]')).toContainText('1 /');
    await expect(page.locator('.exercise').first().locator('.set-row input').nth(1)).toHaveValue('10');
    await page.locator('[data-group="triceps"] > summary').click();
    await page.locator('[data-group="triceps"] .icon-button').first().click();
    await page.getByRole('button',{name:'Убрать из тренировки',exact:true}).click();
    await page.getByRole('button',{name:'Убрать',exact:true}).last().click();
    await expect(page.locator('[data-group="triceps"] .exercise')).toHaveCount(0);
    await page.locator('[data-workout-energy]').click();
    await page.getByLabel(/^Масса тела, кг/).fill('80');
    await page.getByLabel(/^Интенсивность тренировки/).selectOption('vigorous');
    await page.getByLabel(/^Длительность тренировки, минуты/).fill('60');
    await page.getByRole('button',{name:'Сохранить параметры',exact:true}).click();
    await expect(page.locator('[data-workout-energy]')).toHaveText('≈ 420 ккал');
    await page.getByRole('button',{name:'Завершить тренировку',exact:true}).click();
    await saved();
    await expect(page.locator('.energy-total')).toHaveText('≈ 420 ккал');
    await expect(page.locator('.result-entry')).toHaveCount(1);
    await page.getByRole('button',{name:'Неделя',exact:true}).click();
    await expect(page.getByText('Тренировки недели',{exact:true})).toBeVisible();
    await expect(page.locator('.history-item')).toHaveCount(1);
    await expect(page.locator('.energy-total')).toHaveText('≈ 420 ккал');
    await page.getByRole('button',{name:'День',exact:true}).click();
    await page.getByRole('button',{name:'Изменить',exact:true}).click();
    await page.locator('.exercise').first().locator('.set-row input').nth(1).fill('12');
    await page.getByRole('button',{name:'Сохранить изменения',exact:true}).click();
    await expect(page.locator('.result-sets')).toContainText('12');
    await saved();await page.reload();await saved();
    await expect(page.locator('.energy-total')).toHaveText('≈ 420 ккал');
    await page.getByRole('button',{name:'День',exact:true}).click();
    await page.getByRole('button',{name:'Повторить',exact:true}).click();
    await expect(page.locator('.exercise').first().locator('.set-row input').nth(1)).toHaveValue('');
    await expect(page.locator('[data-finish]')).toBeDisabled();
    // Seed only this disposable browser profile to exercise a week spanning two years.
    await saved();
    await page.evaluate(async()=>{
      const {loadData,saveData}=await import('./storage.js?v=20260918-1');
      const data=await loadData(),source=data.workouts[0];
      data.workouts=['2025-12-28','2025-12-29','2026-01-04','2026-01-05'].map((date,index)=>({...structuredClone(source),id:`boundary-${index}`,date}));
      data.draft=null;await saveData(data);
    });
    await page.reload();await saved();
    await page.getByRole('button',{name:'Дашборд',exact:true}).click();
    await page.getByRole('button',{name:'Неделя',exact:true}).click();
    await page.getByLabel('Период дашборда').fill('2026-01-01');
    await expect(page.locator('.history-item')).toHaveCount(2);
    await expect(page.locator('.energy-total')).toHaveText('≈ 840 ккал');
    await expect(page.locator('svg.chart [role="button"]')).toHaveCount(2);
    await page.getByRole('button',{name:'День',exact:true}).click();
    await expect(page.getByLabel('Период дашборда')).toHaveValue('2026-01-01');
    await expect(page.locator('.energy-total')).toHaveText('≈ 0 ккал');
    await page.getByRole('button',{name:'Месяц',exact:true}).click();
    await expect(page.locator('.history-item')).toHaveCount(2);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    assert.deepEqual(errors,[]);
    console.log('UI passed: nested back/escape/search, automatic counting, persistence, empty group, completion, calories, week, edit, repeat, mobile overflow.');
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
